version: '3'

services:
  
  react-server:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react-js
    stdin_open: true
    volumes:
       - .:/home/app
       - ./node_modules
